### PR TITLE
testing more php version

### PR DESCRIPTION
**Pull request by TheTesla**
I changed the php version in .travis.yml, but it works only for version 7.1 - maybe in newer versions it installs php-fpm by default...

### CODE REVIEW

**Comment by pschuele** [comment]
i think, we can drop php 7.0 here - it is no longer supported with the upcoming version 2020.03.1.

php 7.2 + 7.3 should work - I'm a little bit confused about the phpunit errors - which version is used by travis?

**Comment by TheTesla** [comment]
On an ubuntu 18.04 installation php 7.2 is working, but on this travis setup not. I think, choosing php 7.2 or 7.3 on travis it installs incompatible dependencies or configurations.

**Comment by pschuele** [comment]
maybe we should update phpunit to 6.5+ https://github.com/sebastianbergmann/phpunit/issues/2887

**Comment by pschuele** [comment]
we moved to github actions with https://github.com/tine20/tine20/pull/7269. this should not be needed any more.

**Pull request closed without merging**
