### PR TITLE
fixing Thunderbird 78 CalDAV Issue - #7198

### PR DESCRIPTION
**Pull request by sbaumgartner75**
Fix for Issue #7198

### CODE REVIEW

**Comment by sbaumgartner75** [comment]
Once in Event and once in Task.

**Comment by lab-at-nohl** [comment]
> Once in Event and once in Task.

I ment the changed line for the Event ;-) If it does any difference, maybe ordering is important?

`const HEADER_MATCH = '/ (Thunderbird|Lightning|Iceowl|Thunderbird)\/(?P<version>\S+)/';`

**Comment by sbaumgartner75** [comment]
Ok, that’s nonsense. Will fix that in the evening

**Review by pschuele — APPROVED** [review]
looks good, thanks for the PR

**Pull request merged**
