### PR TITLE
refactor(CoreData): change switch-case to simple if statement

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Interesting, CI fails now but nothing was changed in the files which could produce this.
https://travis-ci.org/tine20/tine20/builds/563781631#L439

**Comment by pschuele** [comment]
hi @DanielRuf 
could you please rebase your change to make the ci run again? maybe this was a random fail.

**Comment by DanielRuf** [comment]
Hi @pschuele,

this seems to happen with all PRs after I push more than once.
Even when there are unrelated changes.
See https://github.com/tine20/tine20/pull/7061

**Comment by DanielRuf** [comment]
Hi @pschuele,

Ok, I'll try to rebase and check again.

**Comment by pschuele** [comment]
ah, I now understand the problem. the Timetracker test testSearchTimesheetsByStartTime fails if it is started a short time (0-1 hour) after midnight. will fix that.

**Comment by DanielRuf** [comment]
> ah, I now understand the problem. the Timetracker test testSearchTimesheetsByStartTime fails if it is started a short time (0-1 hour) after midnight. will fix that.

Ah, that explains it. Makes sense. Thanks for the info. Then I'll wait.

Reminds me of similar issues of a datepicker that I maintain =)

**Comment by pschuele** [comment]
> Ah, that explains it. Makes sense. Thanks for the info. Then I'll wait.

no need to wait. I'll check the travis builds - if only this test fails, I'll consider it as passed.

> Reminds me of similar issues of a datepicker that I maintain =)

:)

**Comment by pschuele** [comment]
I just had a second look at the change. the code in the function makes no sense - i would prefer, we completely remove the class CoreData_Preference as it is not used (CoreData has no user preferences yet).

**Pull request closed without merging**
