### PR TITLE
feature: drop pgsql / oracle, require mysql 5.7.5 / mariadb 10.0.5

### PR DESCRIPTION
**Pull request by paulmhh**
Change-Id: Ic20644162b295c7a0720e36989c484eda6db2146

### CODE REVIEW

**Comment by ravermeister** [comment]
I Don't understand why this is considered a feature. Postgres is a good database. And suppirting more than one database increases the Usage of the product

**Comment by paulmhh** [comment]
Postgres certainly is a good database, but the main focus has always been on mysql. DBAL are usually an illusion. It works for very simple queries. It just does not work for complex queries that need optimization. And it most certainly does not work when it comes to more special features like full text indexes, DB specific constraints like index sizes, etc.

Same as dropping PHP5.6 is a big big feature (it opens the world of PHP7), dropping DBAL opens the world of MySQL (there are more appealing worlds, agreed, same for PHP, it is the most ugly language of the successful ones... but this is what we use, PHP7 and MySQL5.7)

**Comment by ravermeister** [comment]
by the way you could have the benefits if you like:
https://wiki.postgresql.org/wiki/Foreign_data_wrappers
and https://github.com/EnterpriseDB/mysql_fdw

**Comment by shochdoerfer** [comment]
@ravermeister unfortunately that does not work with Tine 2.0 due to Zend\Db magic. I tried that a few years back by trying to move our MySQL Tine 2.0 instance over to PostgreSQL. Zend\Db throws some exceptions in the metadata handling as that either seems not work work with FWD or works differently than expected by Zend\Db.

**Pull request merged**
